name: SearchX_RU Release

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-10.15, windows-2019, ubuntu-18.04 ]
        node-version: [ 14.x ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Load private files
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: src/private/StatisticsApi.js
          contents: ${{ secrets.STATISTICS_API }}
          write-mode: overwrite
      - name: Use Node.js ${{matrix.node-version}} in ${{matrix.os}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Download packages
        run: npm install
      - name: Build project
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run electron:build
